defaults: &defaults
  adapter: mysql2
  username: root
  password: "123456"
  encoding: utf8

production:
  database: ftw
  <<: *defaults

development:
  database: ftw
  <<: *defaults

test:
  database: ftw
  <<: *defaults